ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/common
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/sensor/io
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/sensor/cci
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/msm_ais_diag
obj-$(CONFIG_MSM_AIS) += msm_ais_mgr.o
