ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/isp/
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/sensor/io
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/common
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/msm_buf_mgr/
obj-$(CONFIG_MSM_AIS_CPP) += msm_cpp_soc.o msm_cpp.o
