ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/common
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/sensor/io
obj-$(CONFIG_MSM_AIS) += msm_ispif.o
