ccflags-y += -I $(srctree)/drivers/media/video/msm
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/common
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/pproc/cpp
ccflags-y += -I $(srctree)/drivers/media/platform/msm/ais/msm_buf_mgr/

obj-$(CONFIG_MSM_AIS_FD) += msm_fd_dev.o msm_fd_hw.o
